# Generated by Django 2.0.2 on 2018-03-10 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('user_one', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
